
interface MKTSales {
  'FILIAL': string,
  'CIDADE': string,
  'TIPO DE VENDA': string,
  'DATA DA VENDA': Date,
  'VALOR DA VENDA': Number,
  '(%) VENDA': number,
  'COMISSAO': number,
  'BONUS': number,
  'VALOR DO SINAL': number | string,
  'DATA PAG SINAL': Date | string,
  'ORIGEM': string,
  'TIPO IMOVEL': string,
  'IMOVEL/UNIDADE': string,
  'BAIRRO': string,
  'CONSTRUTORA': string,
  'CLIENTE VENDEDOR - NOME': string,
  'CLIENTE VENDEDOR - DATA DE NASCIMENTO': Date | String,
  'CLIENTE VENDEDOR - EMAIL': string,
  'CLIENTE VENDEDOR - TELEFONE': string,
  'CLIENTE VENDEDOR - PROFISSAO': string,
  'CLIENTE VENDEDOR - ESTADO CIVIL': string,
  'CLIENTE COMPRADOR - NOME': string,
  'CLIENTE COMPRADOR - DATA DE NASCIMENTO': Date
  'CLIENTE COMPRADOR - EMAIL': string,
  'CLIENTE COMPRADOR - TELEFONE': string,
  'CLIENTE COMPRADOR - PROFISSAO': string,
  'CLIENTE COMPRADOR - ESTADO CIVIL': string,
  'DIRETORES': string,
  'COOREDENADOR': string,
  'CAPTADORES': string,
  'VENDEDORES': string,
  'SATUS': string,
  'TIPO PAGAMENTO': string,
  '1º PARCELA': number | string,
  '1º PARCELA DT PAG': Date | string,
  '2º PARCELA': number | string,
  '2º PARCELA DT PAG': Date | string,
  '3º PARCELA': number | string,
  '3º PARCELA DT PAG': Date | string,
  '4º PARCELA': number | string,
  '4º PARCELA DT PAG': Date | string,
  '5º PARCELA': number | string,
  '5º PARCELA DT PAG': Date | string,
}

export default interface IRequestMKTDashboardDTO {
  mktSales: MKTSales[]
}
